# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sudo
tagline:          'Personal blog'
description:      'My different stuff'
url:              http://sudosu.github.io

author:
  name:           'Oleg Popadiuk'
  url:            https://twitter.com/superdodman

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/sudosu
